services:
  Madikon\GrumphpComposerAudit\Task\ComposerAudit:
    class: Madikon\GrumphpComposerAudit\Task\ComposerAudit
    arguments:
      - '@process_builder'
      - '@formatter.raw_process'
    tags:
      - { name: grumphp.task, task: composer_audit }
